const fs = require('fs');
const path = require('path');

const VIEWS_DIR = path.join(__dirname, '..', 'views');
const OUT_FILE = path.join(__dirname, '..', 'worker', 'views.bundle.cjs');

function readAllViews(dir) {
  const views = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      Object.assign(views, readAllViews(full));
    } else if (entry.name.endsWith('.ejs')) {
      const rel = path.relative(VIEWS_DIR, full).replace(/\\/g, '/');
      const name = rel.replace(/\.ejs$/, '');
      views[name] = fs.readFileSync(full, 'utf8');
    }
  }
  return views;
}

function resolveIncludes(template, views, resolved = new Set()) {
  return template.replace(/<%-?\s*include\(\s*['"]([^'"]+)['"]\s*(?:,\s*(\{[^}]*\}))?\s*\)\s*%>/g, (match, incPath, dataExpr) => {
    let key = incPath.replace(/^\.\.\//g, '').replace(/^\.\//g, '');
    if (resolved.has(key)) return '';
    resolved.add(key);
    if (!views[key]) return `<!-- missing include: ${key} -->`;
    let inc = views[key];
    inc = resolveIncludes(inc, views, resolved);
    return inc;
  });
}

function extractVarNames(template) {
  const vars = new Set();
  vars.add('flash');

  // Data shared via partials (navbar, flash, footer) must always be bound from data
  vars.add('isAdmin');
  vars.add('notifications');
  vars.add('notifCount');

  // Find variables declared with const/let/var in template code blocks
  const declared = new Set();
  const declRegex = /<%\s*(?:const|let|var)\s+([a-zA-Z_]\w*)/g;
  let dm;
  while ((dm = declRegex.exec(template)) !== null) {
    declared.add(dm[1]);
  }

  const varRegex = /<%[-=]?\s*([\s\S]*?)\s*[-=]?%>/g;
  let m;
  while ((m = varRegex.exec(template)) !== null) {
    const code = m[1];
    const idents = code.match(/\b([a-zA-Z_]\w*)\b/g) || [];
    const jsKeywords = new Set(['var','let','const','function','if','else','return','for','while','do','switch','case','break','continue','new','this','typeof','instanceof','in','of','try','catch','finally','throw','null','undefined','true','false','void','delete','class','extends','super','import','export','default','from','async','await','yield','static','get','set']);
    for (const id of idents) {
      if (!jsKeywords.has(id) && !id.startsWith('__') && id !== 'flash' && !declared.has(id)) {
        vars.add(id);
      }
    }
  }
  return [...vars];
}

function compileEjsToFunction(name, template, allViews) {
  const resolved = new Set();
  let html = template;
  html = resolveIncludes(html, allViews, resolved);

  const varNames = extractVarNames(template);
  const varDecls = varNames.map(v => `var ${v} = __data.${v};`).join('\n  ');

  let buf = 'var __o = "";\n';
  let pos = 0;

  const regex = /(<%[-=]?)([\s\S]*?)([-=]?%>)/g;
  let m;
  while ((m = regex.exec(html)) !== null) {
    if (m.index > pos) {
      const literal = html.slice(pos, m.index).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
      buf += `__o += \`${literal}\`;\n`;
    }
    pos = m.index + m[0].length;

    const open = m[1];
    const inner = m[2];

    if (open === '<%=' || open === '<%-') {
      buf += `__o += ${inner.trim()};\n`;
    } else if (open === '<%') {
      buf += inner + '\n';
    }
  }
  if (pos < html.length) {
    const literal = html.slice(pos).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
    buf += `__o += \`${literal}\`;\n`;
  }

  const fn = `(function(__data) {
  ${varDecls}
  var __e = (v) => v == null ? '' : String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  ${buf}
  return __o;
})`;
  return fn;
}

function main() {
  const views = readAllViews(VIEWS_DIR);
  const count = Object.keys(views).length;

  let output = `// Auto-generated by build-views.js — do not edit\n`;
  output += `const templates = {};\n\n`;

  for (const [name, template] of Object.entries(views)) {
    const fn = compileEjsToFunction(name, template, views);
    output += `templates['${name}'] = ${fn};\n\n`;
  }

  output += `function render(name, data) {
  const fn = templates[name];
  if (!fn) throw new Error('View not found: ' + name);
  return fn(data);
}

module.exports = { render, templates };
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`Built ${count} views -> ${OUT_FILE}`);
}

main();
